[2025-01-31T02:52:32.276+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T02:52:32.296+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_and_insert_csv_to_postgres_with_branch_adjusted.validate_records_task manual__2025-01-31T02:52:20.519782+00:00 [queued]>
[2025-01-31T02:52:32.304+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_and_insert_csv_to_postgres_with_branch_adjusted.validate_records_task manual__2025-01-31T02:52:20.519782+00:00 [queued]>
[2025-01-31T02:52:32.306+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-01-31T02:52:32.319+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): validate_records_task> on 2025-01-31 02:52:20.519782+00:00
[2025-01-31T02:52:32.328+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T02:52:32.330+0000] {standard_task_runner.py:72} INFO - Started process 130 to run task
[2025-01-31T02:52:32.331+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_and_insert_csv_to_postgres_with_branch_adjusted', 'validate_records_task', 'manual__2025-01-31T02:52:20.519782+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/read_file_updated.py', '--cfg-path', '/tmp/tmp19oz5dne']
[2025-01-31T02:52:32.332+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask validate_records_task
[2025-01-31T02:52:32.377+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_and_insert_csv_to_postgres_with_branch_adjusted.validate_records_task manual__2025-01-31T02:52:20.519782+00:00 [running]> on host e2498a6c8083
[2025-01-31T02:52:32.445+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_and_insert_csv_to_postgres_with_branch_adjusted' AIRFLOW_CTX_TASK_ID='validate_records_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T02:52:20.519782+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T02:52:20.519782+00:00'
[2025-01-31T02:52:32.447+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-31T02:52:32.448+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-31T02:52:32.449+0000] {logging_mixin.py:190} INFO - Current task name:validate_records_task state:running start_date:2025-01-31 02:52:32.297742+00:00
[2025-01-31T02:52:32.450+0000] {logging_mixin.py:190} INFO - Dag name:validate_and_insert_csv_to_postgres_with_branch_adjusted and current dag run status:running
[2025-01-31T02:52:32.451+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T02:52:32.494+0000] {logging_mixin.py:190} INFO - Rejected record in file invalid_records.csv: {'emp_id': 'E001', 'name': 'John', 'Surname': 'Doe', 'Location': 'New York', 'city': 'NY', 'pin': 12345, 'doj': '12-01-2020'}, Reason: Invalid pin
[2025-01-31T02:52:32.495+0000] {logging_mixin.py:190} INFO - Rejected record in file invalid_records.csv: {'emp_id': 'E002', 'name': 'Alice', 'Surname': 'Smith123', 'Location': 'Los Angeles', 'city': 'CA', 'pin': 654321, 'doj': '05-06-2018'}, Reason: Name or Surname contains digits
[2025-01-31T02:52:32.496+0000] {logging_mixin.py:190} INFO - Rejected record in file invalid_records.csv: {'emp_id': 'E003', 'name': 'Robert', 'Surname': 'Brown', 'Location': 'Chicago', 'city': 'IL', 'pin': 111222, 'doj': '2019-11-23'}, Reason: time data '2019-11-23' does not match format '%d-%m-%Y'
[2025-01-31T02:52:32.497+0000] {logging_mixin.py:190} INFO - Rejected record in file invalid_records.csv: {'emp_id': 'E004', 'name': 'Mary', 'Surname': 'Johnson', 'Location': 'Houston', 'city': 'TX', 'pin': 333444, 'doj': '15-02-202'}, Reason: time data '15-02-202' does not match format '%d-%m-%Y'
[2025-01-31T02:52:32.529+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-31T02:52:32.551+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T02:52:32.551+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=validate_and_insert_csv_to_postgres_with_branch_adjusted, task_id=validate_records_task, run_id=manual__2025-01-31T02:52:20.519782+00:00, execution_date=20250131T025220, start_date=20250131T025232, end_date=20250131T025232
[2025-01-31T02:52:32.562+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-31T02:52:32.566+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-31T02:52:32.567+0000] {logging_mixin.py:190} INFO - Dag name:validate_and_insert_csv_to_postgres_with_branch_adjusted queued_at:2025-01-31 02:52:20.542511+00:00
[2025-01-31T02:52:32.568+0000] {logging_mixin.py:190} INFO - Task hostname:e2498a6c8083 operator:PythonOperator
[2025-01-31T02:52:32.588+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T02:52:32.612+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-31T02:52:32.615+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
